### ISSUE TITLE
Cart cleared and product added to cart on each product page

### ISSUE THREAD

**Issue by Kurblin** [krokedil/klarna-instant-shopping-for-wordpress#2]
Every time I visit a product page with KIS enabled, the cart clears and the product of that product page is added to the cart.

The expected behavior is that the cart is not cleared and that no product is added to the cart unless the customer clicks on "add to cart". Is this possible?

**Comment by NiklasHogefjord** [comment]
Hi @Kurblin, I will look into this and improve the flow. I'll get back in this issue later today with a report.

**Comment by NiklasHogefjord** [comment]
Hi again,
Version 0.4.3 is now available. This version should fix the issue.
